services:
  server:
    build: .
    ports:
      - "8080:80"
  mongo:
    image: mongo:5-focal
    restart: always
    environment:
      MONGO_INITDB_DATABASE: identidrunk
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - dbdata:/data/db
  grafana:
    image: grafana/grafana:8.2.6
    ports:
      - 4000:3000
    user: '104'
    volumes:
      - grafanadata:/var/lib/grafana

volumes:
  dbdata: {}
  grafanadata: {}
