services:
  server:
    build: .
    ports:
      - "8080:80"
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: identidrunk
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    volumes:
      - dbdata:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana:8.2.6
    ports:
      - 3000:3000
    user: '104'
    volumes:
      - grafanadata:/var/lib/grafana

volumes:
  dbdata: {}
  grafanadata: {}
