services:
  server:
    build: ./deno
    restart: always
    depends_on:
      - database
    ports:
      - 4000:4000
    container_name: identidrunkserver
    environment:
      DB_HOST: database
      DB_DATABASE: identidrunk
      DB_USER: identidrunkuser
      DB_PASSWORD: example

  database:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: identidrunk
      POSTGRES_USER: identidrunkuser
      POSTGRES_PASSWORD: example
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
  grafana:
    image: grafana/grafana:8.2.6
    ports:
      - 3000:3000
    user: '104'
    volumes:
      - grafanadata:/var/lib/grafana

volumes:
  dbdata: null
  grafanadata: null
